version: '3'

services:
  database-pg:
    image: postgres:12.8-bullseye
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo-postgres
      POSTGRES_USER: postgre
    ports:
      - 5432:5432

  nodata-mongo:
    image: mongo:5.0.3-focal
    ports:
      - 27017:27017

  app:
    image: demo-app:1.0
    build: .
    depends_on:
      - database-pg
      - nodata-mongo
    environment:
      SPRING_PORT: 20001
      POSTGRE_SERVER: database-pg
      POSTGRE_PORT: 5432
      POSTGRE_DB: demo-postgres
      POSTGRE_USER: postgre
      POSTGRE_PASSWORD: root
      MONGO_URL: nodata-mongo
      MONGO_PORT: 27017
      MONGO_DATA: mongo_local
      MONGO_USER_AUTH: admin