server:
  port: ${SPRING_PORT:20001}
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRE_SERVER:localhost}:${POSTGRE_PORT:5432}/${POSTGRE_DB:demo-postgres}
    username: ${POSTGRE_USER:postgre}
    password: ${POSTGRE_PASSWORD:root}
    validationQuery: SELECT 1
    testOnBorrow: true
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: ${MONGO_USER_AUTH:admin}
      uri: mongodb://${MONGO_URL:127.0.0.1}:${MONGO_PORT:27017}/${MONGO_DATA:mongo-test}?authSource=${MONGO_USER_AUTH:admin}
      database: ${MONGO_DATA:mongo-test}
      tenant-prefix: ${MONGO_DATA:mongo-test}
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      show_sql: true
      format_sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect